apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyp
spec:
  selector:
    matchLabels:
      app: hyp
  replicas: 2
  template:
    metadata:
      labels:
        app: hyp
    spec:
      containers:
      - name: hyp
        image: nginx

